### PR TITLE
MNT: rebuild v3.5.5 to support multiple epicscorelibs versions

### PR DESCRIPTION
**Pull request by klauer**
## Changes

* Rebuilds v3.5.5 in an attempt to support multiple epicscorelibs versions by way of `conda_build_config.yaml`
* Made an initial attempt at v4.x but now realize it was premature: the introduction of pvxs adds a lot more complexity
* I removed two ex-SLAC'ers as maintainers and added myself (still at SLAC despite all odds). 
   * If either want to remain here, of course I can revert that part
* Switched from using GitHub archives to using PyPI archives, which have a stable hash
   * But unfortunately the MANIFEST wasn't set properly for p4p v3.5.5 and didn't include `LICENSE`; so it's been added here for now.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by klauer** [comment]
Building with pvxs appears to be another can of worms. Going back to v3.5.5 and if that fails miserably, I close this and run away

**Review by jacquelinegarrahan — APPROVED** [review]
Thanks for noticing this Ken!

**Comment by jacquelinegarrahan** [comment]
> Thanks for noticing this Ken!

I hope you're well!

**Comment by klauer** [comment]
> I hope you're well!

Thanks, Jackie - all's good here, and same to you! Congrats again on your new role! 🎉

**Review by chrisvam — APPROVED** [review]

**Comment by klauer** [comment]
@chrisvam, would you mind merging this PR?

**Pull request merged**
